addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libwxgtk2.8-dev
      - libgtk2.0-dev
      - python-imaging
      - python-mysqldb
      - python-networkx
      - python-pip
      - python-tk
      - python-wxgtk2.8
env:
  - LC_ALL="en_US.UTF-8"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
language: python
notifications:
  email: false
python:
  - 2.7
sudo: false
virtualenv:
  system_site_packages: true
install:
  - pip install --upgrade pip
  - pip install --requirement requirements.txt
  - pip freeze
script:
  - python setup.py test
